CICD

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -1,6 +1,6 @@
 name: Group CICD
 
-on: [push]
+on: [push, pull_request]
 
 jobs:
   build-and-test:
@@ -11,19 +11,19 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           python-version: '3.11'  
 
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          python -m $VENV venv
+          source $VENV/bin/activate
+          pip install -r requirements.txt || echo "No requirements.txt found or installation failed"
+
+          
 
       - name: Run tests
         run: |
-          echo "Running tests..."
-          if [ -d tests ]; then pytest tests || echo "No tests found or tests failed"; else echo "No test folder"; fi
-
-      - name: Print Group Message
-        run: echo "This is our group workflow"
+          source $VENV/bin/activate
+          pytest 
